# Generated by Django 4.1 on 2022-08-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ready_made', '0001_initial'),
        ('userextend', '0002_userextend_date_of_birth'),
        ('services', '0003_alter_servicelogo_price_alter_servicelogo_turnaround'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('logo_name', models.CharField(max_length=100)),
                ('logo_slogan', models.CharField(blank=True, max_length=100)),
                ('company_description', models.TextField(blank=True, max_length=3000)),
                ('company_industry', models.CharField(blank=True, max_length=100)),
                ('logo_colors', models.TextField(blank=True, max_length=1000)),
                ('project_description', models.TextField(max_length=1000)),
                ('project_image_1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('other_notes', models.TextField(blank=True, max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend')),
                ('ready_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ready_made.readylogo')),
                ('service_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.servicelogo')),
            ],
        ),
    ]
