# Generated by Django 4.1 on 2022-08-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectlogo',
            old_name='project_image_1',
            new_name='optional_project_image_1',
        ),
    ]
