# Generated by Django 4.1 on 2022-08-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0004_userprofile_company_alter_userprofile_user'),
        ('projects', '0007_alter_projectlogo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLogoClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectlogo')),
            ],
        ),
    ]
