# Generated by Django 4.1 on 2022-09-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_projectlogoclient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectLogoClient',
        ),
    ]
