# Generated by Django 4.1 on 2022-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_delete_projectlogoclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogo',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Invited', 'Invited'), ('Started', 'Started'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], max_length=9, null=True),
        ),
    ]
