# Generated by Django 4.1 on 2022-09-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0007_alter_userprofile_profile_image'),
        ('projects', '0011_projectlogo_style_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlogo',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend'),
        ),
    ]
