# Generated by Django 4.1 on 2022-09-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0007_alter_userprofile_profile_image'),
        ('projects', '0013_rename_style_attribute_projectlogo_classic_or_modern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlogo',
            name='id',
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='company_description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='company_industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='logo_colors',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='logo_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='logo_slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='other_notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='project_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='projectlogo',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend')),
            ],
        ),
        migrations.AddField(
            model_name='projectlogo',
            name='project_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project'),
            preserve_default=False,
        ),
    ]
