# Generated by Django 4.1 on 2022-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectfile_projectactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='status',
            field=models.CharField(choices=[('Reference', 'Reference'), ('In progress', 'In progress'), ('Declined', 'Declined'), ('Final', 'Final')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
