# Generated by Django 4.1 on 2022-09-05 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projectfile_project_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('project_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectfile')),
            ],
        ),
    ]
