# Generated by Django 4.1 on 2022-09-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_commentprojectfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectlogo'),
        ),
    ]
