# Generated by Django 4.1 on 2022-09-08 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_commentprojectfile_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentprojectfile',
            name='project_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectfile'),
        ),
    ]
