# Generated by Django 4.1 on 2022-09-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_commentprojectfile_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='file_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
