# Generated by Django 4.1 on 2022-09-09 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_projectfile_file_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentprojectfile',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectlogo'),
        ),
    ]
