# Generated by Django 4.1 on 2022-09-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_commentprojectfile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactivity',
            name='owner',
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectlogo'),
        ),
    ]
