# Generated by Django 4.1 on 2022-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_remove_projectactivity_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
