# Generated by Django 4.1 on 2022-09-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projectactivity_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectlogo'),
        ),
    ]
