# Generated by Django 4.1 on 2022-09-09 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0007_alter_userprofile_profile_image'),
        ('projects', '0025_alter_projectactivity_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectactivity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userextend.userextend'),
        ),
    ]
