# Generated by Django 4.1 on 2022-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_commentprojectfile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentprojectfile',
            name='owner',
        ),
    ]
