# Generated by Django 4.1 on 2022-09-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_projectfile_project_final_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='project_file',
            field=models.ImageField(blank=True, null=True, upload_to='projects/files/'),
        ),
    ]
