# Generated by Django 4.1 on 2022-09-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_projectfile_project_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='project_final_file',
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='projects/files/'),
        ),
    ]
