# Generated by Django 4.1 on 2022-09-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_alter_projectpayment_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectlogo',
            options={'ordering': ['id']},
        ),
    ]
