# Generated by Django 4.1 on 2022-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_description', models.TextField(max_length=3000)),
                ('service_deliverable', models.TextField(max_length=3000)),
                ('turnaround', models.IntegerField()),
                ('price', models.IntegerField()),
                ('service_image_1', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
