# Generated by Django 4.1 on 2022-08-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceLogo',
        ),
    ]
