# Generated by Django 4.1 on 2022-08-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_service_servicelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelogo',
            name='price',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicelogo',
            name='turnaround',
            field=models.CharField(max_length=50),
        ),
    ]
