# Generated by Django 4.1 on 2022-08-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=50)),
                ('logo_description', models.TextField(max_length=1000)),
                ('company_description', models.TextField(blank=True, max_length=1000)),
                ('company_industry', models.CharField(blank=True, max_length=50)),
                ('logo_image_1', models.ImageField(null=True, upload_to='readylogo/')),
                ('logo_image_2', models.ImageField(blank=True, null=True, upload_to='readylogo/')),
                ('logo_image_3', models.ImageField(blank=True, null=True, upload_to='readylogo/')),
                ('logo_image_4', models.ImageField(blank=True, null=True, upload_to='readylogo/')),
                ('logo_image_5', models.ImageField(blank=True, null=True, upload_to='readylogo/')),
                ('logo_image_6', models.ImageField(blank=True, null=True, upload_to='readylogo/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
