# Generated by Django 4.1 on 2022-08-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_made', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readylogo',
            old_name='logo_image_2',
            new_name='optional_logo_image_2',
        ),
        migrations.RenameField(
            model_name='readylogo',
            old_name='logo_image_3',
            new_name='optional_logo_image_3',
        ),
        migrations.RenameField(
            model_name='readylogo',
            old_name='logo_image_4',
            new_name='optional_logo_image_4',
        ),
        migrations.RenameField(
            model_name='readylogo',
            old_name='logo_image_5',
            new_name='optional_logo_image_5',
        ),
        migrations.RenameField(
            model_name='readylogo',
            old_name='logo_image_6',
            new_name='optional_logo_image_6',
        ),
    ]
