# Generated by Django 4.1 on 2022-09-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ready_made', '0002_rename_logo_image_2_readylogo_optional_logo_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readylogo',
            options={'ordering': ['id']},
        ),
    ]
