# Generated by Django 4.1 on 2022-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
