# Generated by Django 4.1 on 2022-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0004_userprofile_company_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to='profiles/'),
        ),
    ]
