# Generated by Django 4.1 on 2022-09-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profiles/'),
        ),
    ]
