# Generated by Django 4.1 on 2022-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfoliologo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliologo',
            name='company_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='portfoliologo',
            name='logo_description',
            field=models.TextField(max_length=1000),
        ),
    ]
