# Generated by Django 4.1 on 2022-09-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_logo_image_2_portfoliologo_optional_logo_image_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliologo',
            options={'ordering': ['id']},
        ),
    ]
