# Generated by Django 4.1 on 2022-08-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_project_image_1_projectlogo_optional_project_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlogo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('started', 'Started'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=9, null=True),
        ),
    ]
